"""Collaborator table created

Revision ID: 766d2c2be55b
Revises: d8a9abffe9dc
Create Date: 2023-08-24 18:13:17.790058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d2c2be55b'
down_revision = 'd8a9abffe9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('access_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collaborator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collaborator_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaborator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collaborator_id'))

    op.drop_table('collaborator')
    # ### end Alembic commands ###
