"""NoteLabel table created

Revision ID: d2172f037cc4
Revises: 766d2c2be55b
Create Date: 2023-08-31 16:48:16.422803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2172f037cc4'
down_revision = '766d2c2be55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_label',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_label', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_label_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_label', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_label_id'))

    op.drop_table('note_label')
    # ### end Alembic commands ###
